apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: test-bck-api
  namespace: test
spec:
  healthCheck:
    checkIntervalSec: 90 
    healthyThreshold: 1
    port: 8081
    requestPath: /
    timeoutSec: 10                     
    type: HTTP
    unhealthyThreshold: 3 